spring:
  application:
    name: project-be
  profiles:
    active: local
  datasource:
    url: jdbc:mariadb://localhost:3307/techtest?allowPublicKeyRetrieval=true&useSSL=false
    username: user
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    exchanges:
      review: review.exchange
    queues:
      reviewCreated: review.created.queue
      reviewUpdated: review.updated.queue
    routing-keys:
      reviewCreated: review.created

# Opzioni aggiuntive
server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.tuo.pacchetto: DEBUG

app:
  allowed-origins:
    - http://localhost:3000
    - http://example.com
